export const RECEIVE_TODO = "RECEIVE_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const RECEIVE_ERROR = "RECEIVE_ERROR";
export const RECEIVE_ALL_POSTS = "RECEIVE_ALL_POSTS";
